db:
    #活动库
    activity-master:
        jdbcUrl: jdbc:mysql://localhost:3306/activity
        username: root
        password: tiger
    activity-slave:
        jdbcUrl: jdbc:mysql://localhost:3306/activity
        username: root
        password: tiger

    #人员库
    crew-master:
        jdbcUrl: jdbc:mysql://localhost:3306/crew
        username: root
        password: tiger
    crew-slave:
        jdbcUrl: jdbc:mysql://localhost:3306/crew
        username: root
        password: tiger

    #项目库
    project-master:
        jdbcUrl: jdbc:mysql://localhost:3306/project
        username: root
        password: tiger
    project-slave:
        jdbcUrl: jdbc:mysql://localhost:3306/project
        username: root
        password: tiger
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapper/*/*/*.xml
logging:
    level:com.example.demo.dao = DEBUG

#使用spring-boot的redis配置
spring:
    redis:
      #jedis:
       # pool:
       #   max-idle: 1
       #   max-wait: 2000
       #   max-active: 2
      #cluster:
      #  nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
      host: localhost
      timeout: 500

    #引入mq配置
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      publisher-confirms: true
      publisher-returns: true

      listener:
        simple:
          acknowledge-mode: manual

#自定义redis配置
customer:
    redis:
     cluster: 127.0.0.1:6379
     timeout: 500
     pool:
        max-idle: 1
        max-wait: 2000
        max-active: 2

retrofit:
    base-url:
      baidu: https://www.baidu.com
      github: https://github.com

#修改默认端口号
server:
  port: 8088